services:
  database:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
  php:
    build: .
    volumes:
      - '.:/srv'
    ports:
      - '80:8000'
    depends_on:
      - 'database'
